* Battleship

  This is a quick implementation of the Battleship game in Python
  
  The game is programmed in a literate style, using Emacs' =org-mode= and
  =noweb=, to allow us to interleave text and code freely. The
  sources are /tangled/ (extracted) from the [[battleship.org]] file (open the file
  in emacs, ensure =ob-python= is available, and invoke the =org-babel-tangle=
  command), and the project can be built and tested from within emacs, by
  executing the following code blocks (of course, this can also be done in the
  command line).

  First, we need to make sure we have all the dependencies (assuming a working
  Python 3 install with a =pip3= available):
  
 #+begin_src sh :exports both :results output
pip3 install -r requirements.txt
 #+end_src

 #+RESULTS:
 #+begin_example
 Collecting Hypothesis==5.6.0 (from -r requirements.txt (line 1))
   Using cached https://files.pythonhosted.org/packages/51/19/0c2931f0ab4da3ac0720a36538515597090178731f74b2c8832a2032687a/hypothesis-5.6.0-py3-none-any.whl
 Collecting Pytest==5.3.5 (from -r requirements.txt (line 2))
   Using cached https://files.pythonhosted.org/packages/a5/c0/34033b2df7718b91c667bd259d5ce632ec3720198b7068c0ba6f6104ff89/pytest-5.3.5-py3-none-any.whl
 Collecting Pytest-cov==2.8.1 (from -r requirements.txt (line 3))
   Using cached https://files.pythonhosted.org/packages/b9/54/3673ee8be482f81527678ac894276223b9814bb7262e4f730469bb7bf70e/pytest_cov-2.8.1-py2.py3-none-any.whl
 Collecting sortedcontainers<3.0.0,>=2.1.0 (from Hypothesis==5.6.0->-r requirements.txt (line 1))
   Using cached https://files.pythonhosted.org/packages/13/f3/cf85f7c3a2dbd1a515d51e1f1676d971abe41bba6f4ab5443240d9a78e5b/sortedcontainers-2.1.0-py2.py3-none-any.whl
 Collecting attrs>=19.2.0 (from Hypothesis==5.6.0->-r requirements.txt (line 1))
   Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
 Collecting wcwidth (from Pytest==5.3.5->-r requirements.txt (line 2))
   Using cached https://files.pythonhosted.org/packages/58/b4/4850a0ccc6f567cc0ebe7060d20ffd4258b8210efadc259da62dc6ed9c65/wcwidth-0.1.8-py2.py3-none-any.whl
 Collecting more-itertools>=4.0.0 (from Pytest==5.3.5->-r requirements.txt (line 2))
   Using cached https://files.pythonhosted.org/packages/72/96/4297306cc270eef1e3461da034a3bebe7c84eff052326b130824e98fc3fb/more_itertools-8.2.0-py3-none-any.whl
 Collecting importlib-metadata>=0.12; python_version < "3.8" (from Pytest==5.3.5->-r requirements.txt (line 2))
   Using cached https://files.pythonhosted.org/packages/8b/03/a00d504808808912751e64ccf414be53c29cad620e3de2421135fcae3025/importlib_metadata-1.5.0-py2.py3-none-any.whl
 Collecting pluggy<1.0,>=0.12 (from Pytest==5.3.5->-r requirements.txt (line 2))
   Using cached https://files.pythonhosted.org/packages/a0/28/85c7aa31b80d150b772fbe4a229487bc6644da9ccb7e427dd8cc60cb8a62/pluggy-0.13.1-py2.py3-none-any.whl
 Collecting packaging (from Pytest==5.3.5->-r requirements.txt (line 2))
   Downloading https://files.pythonhosted.org/packages/62/0a/34641d2bf5c917c96db0ded85ae4da25b6cd922d6b794648d4e7e07c88e5/packaging-20.3-py2.py3-none-any.whl
 Collecting py>=1.5.0 (from Pytest==5.3.5->-r requirements.txt (line 2))
   Using cached https://files.pythonhosted.org/packages/99/8d/21e1767c009211a62a8e3067280bfce76e89c9f876180308515942304d2d/py-1.8.1-py2.py3-none-any.whl
 Collecting coverage>=4.4 (from Pytest-cov==2.8.1->-r requirements.txt (line 3))
   Using cached https://files.pythonhosted.org/packages/6a/58/df86640436e28ca46fa5e93e603c82abb0cba309b37cbaec1e1188ea53a6/coverage-5.0.3-cp36-cp36m-manylinux1_x86_64.whl
 Collecting zipp>=0.5 (from importlib-metadata>=0.12; python_version < "3.8"->Pytest==5.3.5->-r requirements.txt (line 2))
   Using cached https://files.pythonhosted.org/packages/b2/34/bfcb43cc0ba81f527bc4f40ef41ba2ff4080e047acb0586b56b3d017ace4/zipp-3.1.0-py3-none-any.whl
 Collecting pyparsing>=2.0.2 (from packaging->Pytest==5.3.5->-r requirements.txt (line 2))
   Using cached https://files.pythonhosted.org/packages/5d/bc/1e58593167fade7b544bfe9502a26dc860940a79ab306e651e7f13be68c2/pyparsing-2.4.6-py2.py3-none-any.whl
 Collecting six (from packaging->Pytest==5.3.5->-r requirements.txt (line 2))
   Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
 Installing collected packages: sortedcontainers, attrs, Hypothesis, wcwidth, more-itertools, zipp, importlib-metadata, pluggy, pyparsing, six, packaging, py, Pytest, coverage, Pytest-cov
 Successfully installed Hypothesis-5.6.0 Pytest-5.3.5 Pytest-cov-2.8.1 attrs-19.3.0 coverage-5.0.3 importlib-metadata-1.5.0 more-itertools-8.2.0 packaging-20.3 pluggy-0.13.1 py-1.8.1 pyparsing-2.4.6 six-1.14.0 sortedcontainers-2.1.0 wcwidth-0.1.8 zipp-3.1.0
 #+end_example

** Testing 
We can also run the test suite like so:
#+begin_src sh :exports both :results output
pytest --cov=battleship
#+end_src

#+RESULTS:
#+begin_example
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /home/mvr/Devel/Python/battleship
plugins: cov-2.8.1, hypothesis-5.6.0
collected 6 items

battleship/test_ai.py ..                                                 [ 33%]
battleship/test_board.py ...                                             [ 83%]
battleship/test_game.py .                                                [100%]

----------- coverage: platform linux, python 3.6.9-final-0 -----------
Name                       Stmts   Miss  Cover
----------------------------------------------
battleship/__init__.py         6      0   100%
battleship/ai.py              63      0   100%
battleship/board.py          100     23    77%
battleship/cli.py             69     59    14%
battleship/game.py            32      2    94%
battleship/pieces.py          25      6    76%
battleship/player.py          21     11    48%
battleship/ship.py             9      0   100%
battleship/test_ai.py         17      0   100%
battleship/test_board.py      53      0   100%
battleship/test_game.py       16      0   100%
----------------------------------------------
TOTAL                        411    101    75%


============================== 6 passed in 2.78s ===============================
#+end_example

For the testing, I opted for a generative testing approach, using [[https://hypothesis.readthedocs.io/en/latest/index.html][Hypothesis]],
which allows to do fairly comprehensive testing with relatively low effort. The
tests are mostly integration tests; unit testing could be added as needed. The
six tests defined cover most of the actual game code (the CLI code is not
tested, as it would mostly need to be done using =expect= or similar, and it is
too labor-intensive for this project), with a very large number of conditions.

** Playing
   For playing, simply invoke the [[play_battleship]] script.

   
** Documentation

   The annotated source code and rationale has been exported to the
   [[battleship.html]] file. If reading this online on GitHub, it is better to look
   at the [[battleship.org]] file, since GitHub renders =org-mode= quite nicely. If
   on the other hand, you are reading this offline, it is probably better to
   open the HTML export in your browser, for a nicely formatted view.
